name: Verilog Verify

on:
  workflow_dispatch

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Verification Container
        uses: ./.github/actions/verify
      - name: Test Print
        run: echo "hello world"
