name: Verilog Pipe

on:
  workflow_dispatch

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # 1 - Free some space
      - name: Free Space
        run: rm -rf /opt/hostedtoolcache
      # 2 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # 3 - Run verification container
      - name: Run Verification Container
        uses: ./.github/actions/verify
      # 4 - Extract QAR
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}/quartus_project/project.qar
